# Generated by Django 4.0 on 2022-01-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id_iot',
            field=models.CharField(default='FOR_DEBUG', max_length=100),
            preserve_default=False,
        ),
    ]
